# Day-3

## Name : Mukkala Vijaya Rama Krishna Dhanush

## Gmail : mukkaladhanush747@gmail.com

## Ph.No : 8978374568

## Q1:

In [2]:
import numpy as np
ar = np.arange(2, 50, 3)
print(ar)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Q2:

In [6]:
import numpy as np
l1, l2 = [], []
for i in range(5):
    a=int(input())
    l1.append(a)
for i in range(5):
    a=int(input())
    l2.append(a)
a1 = np.array(l1)
a2 = np.array(l2)
ar = np.concatenate((a1,a2))
sa = np.sort(ar)
print(sa)

5
4
6
7
1
3
10
16
12
8
[ 1  3  4  5  6  7  8 10 12 16]


# Q3:

In [8]:
import numpy as np
ar = np.array([[1,2,3],[1,3,5]])
print(ar.ndim)
print(ar.size)
print(ar.shape)

2
6
(2, 3)


# Q4:

In [10]:
import numpy as np
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])   # 1-D array
ar_2d = np.reshape(ar, (2, 5))                  # 2-D array
print(ar_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


# Q5:

In [11]:
import numpy as np
a1 = np.square([1,2,3,4,5])
a2 = np.square([6,7,8,9,10])
print(np.hstack((a1, a2)))
print(np.vstack((a1, a2)))

[  1   4   9  16  25  36  49  64  81 100]
[[  1   4   9  16  25]
 [ 36  49  64  81 100]]


# Q6:

In [13]:
import numpy as np
a1 = np.array([1,4,9,5,6,7,2,5,3,4,6,1,2,9,6,4,5])
u, c = np.unique(a1, return_counts=True)
ar = np.asarray((u, c)).T
print(ar)

[[1 2]
 [2 2]
 [3 1]
 [4 3]
 [5 3]
 [6 3]
 [7 1]
 [9 2]]
